### ISSUE TITLE
Proto library errors

### ISSUE THREAD

**Issue by andrewkatson** [rules-proto-grpc/rules_proto_grpc#128]
I followed the instructions for the following languages and got the an error about missing toolchains for each one or something else. I am on ubuntu 20.04. 

C 
```
ERROR: /home/andrew/.cache/bazel/_bazel_andrew/18a62b1f44478583cd12b8571a2982d5/external/rules_proto_grpc/c/BUILD.bazel:3:13: no such package '@upb//upbc': BUILD file not found in directory 'upbc' of external repository @upb. Add a BUILD file to a directory to mark it as a package. and referenced by '@rules_proto_grpc//c:upb_plugin'
```

Go 
```
ERROR: Traceback (most recent call last):
	File "/home/andrew/KeirosPublic/WORKSPACE", line 190, column 23, in <toplevel>
		go_register_toolchains(
	File "/home/andrew/.cache/bazel/_bazel_andrew/18a62b1f44478583cd12b8571a2982d5/external/io_bazel_rules_go/go/toolchain/toolchains.bzl", line 373, column 5, in go_register_toolchains
		def go_register_toolchains(go_version = DEFAULT_VERSION, nogo = None):
Error: go_register_toolchains() got unexpected keyword argument: version (did you mean 'go_version'?)
ERROR: error loading package '': Encountered error while reading extension file 'deps.bzl': no such package '@bazel_gazelle//': error loading package 'external': Could not load //external package

```

CSharp 
```
no matching toolchains found for types @io_bazel_rules_dotnet//dotnet:toolchain_type_csharp_core
ERROR: Analysis of target '//CurrencyManagement/Proto:currency_management_user_info_response_csharp_proto.dll' failed; build aborted: no matching toolchains found for types @io_bazel_rules_dotnet//dotnet:toolchain_type_csharp_core

```

Android 
```
no matching toolchains found for types @bazel_tools//tools/android:sdk_toolchain_type
ERROR: Analysis of target '//CurrencyManagement/Proto:currency_management_user_info_request_android_proto' failed; build aborted: no matching toolchains found for types @bazel_tools//tools/android:sdk_toolchain_type

```
Objective C 
```
ERROR: /home/andrew/.cache/bazel/_bazel_andrew/18a62b1f44478583cd12b8571a2982d5/external/local_config_cc/BUILD:47:19: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'darwin_x86_64'
ERROR: Analysis of target '//Proto:coin_objc_proto' failed; build aborted: Analysis of target '@local_config_cc//:toolchain' failed
```

Ruby 
```
ERROR: An error occurred during the fetch of repository 'org_ruby_lang_ruby_toolchain':
   Traceback (most recent call last):
	File "/home/andrew/.cache/bazel/_bazel_andrew/18a62b1f44478583cd12b8571a2982d5/external/bazelruby_rules_ruby/ruby/private/toolchains/ruby_runtime.bzl", line 120, column 35, in _ruby_runtime_impl
		ruby = ruby_repository_context(ctx, interpreter_path)
	File "/home/andrew/.cache/bazel/_bazel_andrew/18a62b1f44478583cd12b8571a2982d5/external/bazelruby_rules_ruby/ruby/private/toolchains/repository_context.bzl", line 42, column 40, in ruby_repository_context
		interpreter_path = interpreter_path.realpath
Error: /home/andrew/.cache/bazel/_bazel_andrew/18a62b1f44478583cd12b8571a2982d5/external/org_ruby_lang_ruby_toolchain/build/bin (No such file or directory)
ERROR: Error fetching repository: Traceback (most recent call last):
	File "/home/andrew/.cache/bazel/_bazel_andrew/18a62b1f44478583cd12b8571a2982d5/external/bazelruby_rules_ruby/ruby/private/toolchains/ruby_runtime.bzl", line 120, column 35, in _ruby_runtime_impl
		ruby = ruby_repository_context(ctx, interpreter_path)
	File "/home/andrew/.cache/bazel/_bazel_andrew/18a62b1f44478583cd12b8571a2982d5/external/bazelruby_rules_ruby/ruby/private/toolchains/repository_context.bzl", line 42, column 40, in ruby_repository_context
		interpreter_path = interpreter_path.realpath
Error: /home/andrew/.cache/bazel/_bazel_andrew/18a62b1f44478583cd12b8571a2982d5/external/org_ruby_lang_ruby_toolchain/build/bin (No such file or directory)

```

Swift
```
ERROR: Skipping 'Proto:all': while parsing 'Proto:all': error loading package 'Proto': in /home/andrew/.cache/bazel/_bazel_andrew/18a62b1f44478583cd12b8571a2982d5/external/rules_proto_grpc/swift/defs.bzl: in /home/andrew/.cache/bazel/_bazel_andrew/18a62b1f44478583cd12b8571a2982d5/external/rules_proto_grpc/swift/swift_grpc_library.bzl: in /home/andrew/.cache/bazel/_bazel_andrew/18a62b1f44478583cd12b8571a2982d5/external/build_bazel_rules_swift/swift/swift.bzl: in /home/andrew/.cache/bazel/_bazel_andrew/18a62b1f44478583cd12b8571a2982d5/external/build_bazel_rules_swift/swift/internal/swift_library.bzl: cannot load '@bazel_skylib//rules:common_settings.bzl': no such file
WARNING: Target pattern parsing failed.
ERROR: while parsing 'Proto:all': error loading package 'Proto': in /home/andrew/.cache/bazel/_bazel_andrew/18a62b1f44478583cd12b8571a2982d5/external/rules_proto_grpc/swift/defs.bzl: in /home/andrew/.cache/bazel/_bazel_andrew/18a62b1f44478583cd12b8571a2982d5/external/rules_proto_grpc/swift/swift_grpc_library.bzl: in /home/andrew/.cache/bazel/_bazel_andrew/18a62b1f44478583cd12b8571a2982d5/external/build_bazel_rules_swift/swift/swift.bzl: in /home/andrew/.cache/bazel/_bazel_andrew/18a62b1f44478583cd12b8571a2982d5/external/build_bazel_rules_swift/swift/internal/swift_library.bzl: cannot load '@bazel_skylib//rules:common_settings.bzl': no such file

```

D
```
ERROR: /home/andrew/KeirosPublic/Proto/BUILD:32:16: Compiling D library wallet_d_proto failed: (Exit 1): dmd failed: error executing command external/dmd_linux_x86_64/dmd2/linux/bin64/dmd -lib -ofbazel-out/k8-fastbuild/bin/Proto/libwallet_d_proto.a -I. -debug -w -g -Iexternal/com_github_dcarp_protobuf_d/src ... (remaining 7 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox dmd failed: error executing command external/dmd_linux_x86_64/dmd2/linux/bin64/dmd -lib -ofbazel-out/k8-fastbuild/bin/Proto/libwallet_d_proto.a -I. -debug -w -g -Iexternal/com_github_dcarp_protobuf_d/src ... (remaining 7 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
bazel-out/k8-fastbuild/bin/Proto/wallet_d_proto_pb/common/wallet.d(7): Error: module `identifier` is in file 'Security/Proto/identifier.d' which cannot be read
import path[0] = .
import path[1] = external/com_github_dcarp_protobuf_d/src
import path[2] = external/dmd_linux_x86_64/dmd2/src/phobos
import path[3] = external/dmd_linux_x86_64/dmd2/src/druntime/import
import path[4] = /home/andrew/.cache/bazel/_bazel_andrew/18a62b1f44478583cd12b8571a2982d5/external/dmd_linux_x86_64/dmd2/linux/bin64/../../src/phobos
import path[5] = /home/andrew/.cache/bazel/_bazel_andrew/18a62b1f44478583cd12b8571a2982d5/external/dmd_linux_x86_64/dmd2/linux/bin64/../../src/druntime/import
```

Scala
```
ERROR: /home/andrew/KeirosPublic/Proto/BUILD:17:20: scala //Proto:wallet_scala_proto failed: (Exit 1): scalac failed: error executing command bazel-out/k8-opt-exec-2B5CBBC6/bin/external/io_bazel_rules_scala/src/java/io/bazel/rulesscala/scalac/scalac @bazel-out/k8-fastbuild/bin/Proto/wallet_scala_proto_scalac_worker_input
bazel-out/k8-fastbuild/bin/Proto/tmp5639144808957831878/common/wallet/Wallet.scala:15: error: object security is not a member of package common
    userId: _root_.scala.Option[common.security.identifier.Identifier] = _root_.scala.None
                                       ^
bazel-out/k8-fastbuild/bin/Proto/tmp5639144808957831878/common/wallet/Wallet.scala:131: error: object security is not a member of package common
            __userId = Option(_root_.scalapb.LiteParser.readMessage(_input__, __userId.getOrElse(common.security.identifier.Identifier.defaultInstance)))
                                                                                                        ^
bazel-out/k8-fastbuild/bin/Proto/tmp5639144808957831878/common/wallet/Wallet.scala:149: error: object security is not a member of package common
    def getUserId: common.security.identifier.Identifier = userId.getOrElse(common.security.identifier.Identifier.defaultInstance)
                          ^
bazel-out/k8-fastbuild/bin/Proto/tmp5639144808957831878/common/wallet/Wallet.scala:149: error: object security is not a member of package common
    def getUserId: common.security.identifier.Identifier = userId.getOrElse(common.security.identifier.Identifier.defaultInstance)
                                                                                   ^
bazel-out/k8-fastbuild/bin/Proto/tmp5639144808957831878/common/wallet/Wallet.scala:151: error: object security is not a member of package common
    def withUserId(__v: common.security.identifier.Identifier): Wallet = copy(userId = Option(__v))
                               ^
bazel-out/k8-fastbuild/bin/Proto/tmp5639144808957831878/common/wallet/Wallet.scala:203: error: object security is not a member of package common
      __fieldsMap.get(__fields.get(5)).asInstanceOf[_root_.scala.Option[common.security.identifier.Identifier]]
                                                                               ^
bazel-out/k8-fastbuild/bin/Proto/tmp5639144808957831878/common/wallet/Wallet.scala:215: error: object security is not a member of package common
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(6).get).flatMap(_.as[_root_.scala.Option[common.security.identifier.Identifier]])
                                                                                                          ^
bazel-out/k8-fastbuild/bin/Proto/tmp5639144808957831878/common/wallet/Wallet.scala:224: error: object security is not a member of package common
      case 6 => __out = common.security.identifier.Identifier
                               ^
bazel-out/k8-fastbuild/bin/Proto/tmp5639144808957831878/common/wallet/Wallet.scala:244: error: object security is not a member of package common
    def userId: _root_.scalapb.lenses.Lens[UpperPB, common.security.identifier.Identifier] = field(_.getUserId)((c_, f_) => c_.copy(userId = Option(f_)))
                                                           ^
bazel-out/k8-fastbuild/bin/Proto/tmp5639144808957831878/common/wallet/Wallet.scala:244: error: missing parameter type
    def userId: _root_.scalapb.lenses.Lens[UpperPB, common.security.identifier.Identifier] = field(_.getUserId)((c_, f_) => c_.copy(userId = Option(f_)))
                                                                                                                     ^
bazel-out/k8-fastbuild/bin/Proto/tmp5639144808957831878/common/wallet/Wallet.scala:245: error: object security is not a member of package common
    def optionalUserId: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[common.security.identifier.Identifier]] = field(_.userId)((c_, f_) => c_.copy(userId = f_))
                                                                                       ^
bazel-out/k8-fastbuild/bin/Proto/tmp5639144808957831878/common/wallet/Wallet.scala:259: error: object security is not a member of package common
    userId: _root_.scala.Option[common.security.identifier.Identifier]
                                       ^
bazel-out/k8-fastbuild/bin/Proto/tmp5639144808957831878/common/wallet/WalletProto.scala:10: error: object security is not a member of package common
    common.security.identifier.IdentifierProto
           ^
bazel-out/k8-fastbuild/bin/Proto/tmp5639144808957831878/common/wallet/WalletProto.scala:31: error: object security is not a member of package common
      common.security.identifier.IdentifierProto.javaDescriptor
             ^
14 errors found
Build failed
java.lang.RuntimeException: Build failed
	at io.bazel.rulesscala.scalac.ScalacWorker.compileScalaSources(ScalacWorker.java:262)
	at io.bazel.rulesscala.scalac.ScalacWorker.work(ScalacWorker.java:65)
	at io.bazel.rulesscala.worker.Worker.persistentWorkerMain(Worker.java:92)
	at io.bazel.rulesscala.worker.Worker.workerMain(Worker.java:46)
	at io.bazel.rulesscala.scalac.ScalacWorker.main(ScalacWorker.java:32)

```

Rust
```
error[E0433]: failed to resolve: maybe a missing crate `identifier`?
  --> bazel-out/k8-fastbuild/bin/Proto/wallet_rust_proto_pb/wallet.rs:34:54
   |
34 |     pub user_id: ::protobuf::SingularPtrField<super::identifier::Identifier>,
   |                                                      ^^^^^^^^^^ maybe a missing crate `identifier`?

error[E0433]: failed to resolve: maybe a missing crate `identifier`?
   --> bazel-out/k8-fastbuild/bin/Proto/wallet_rust_proto_pb/wallet.rs:184:42
    |
184 |     pub fn get_user_id(&self) -> &super::identifier::Identifier {
    |                                          ^^^^^^^^^^ maybe a missing crate `identifier`?

error[E0433]: failed to resolve: maybe a missing crate `identifier`?
   --> bazel-out/k8-fastbuild/bin/Proto/wallet_rust_proto_pb/wallet.rs:185:57
    |
185 |         self.user_id.as_ref().unwrap_or_else(|| <super::identifier::Identifier as ::protobuf::Message>::default_instance())
    |                                                         ^^^^^^^^^^ maybe a missing crate `identifier`?

error[E0433]: failed to resolve: maybe a missing crate `identifier`?
   --> bazel-out/k8-fastbuild/bin/Proto/wallet_rust_proto_pb/wallet.rs:196:45
    |
196 |     pub fn set_user_id(&mut self, v: super::identifier::Identifier) {
    |                                             ^^^^^^^^^^ maybe a missing crate `identifier`?

error[E0433]: failed to resolve: maybe a missing crate `identifier`?
   --> bazel-out/k8-fastbuild/bin/Proto/wallet_rust_proto_pb/wallet.rs:202:50
    |
202 |     pub fn mut_user_id(&mut self) -> &mut super::identifier::Identifier {
    |                                                  ^^^^^^^^^^ maybe a missing crate `identifier`?

error[E0433]: failed to resolve: maybe a missing crate `identifier`?
   --> bazel-out/k8-fastbuild/bin/Proto/wallet_rust_proto_pb/wallet.rs:210:46
    |
210 |     pub fn take_user_id(&mut self) -> super::identifier::Identifier {
    |                                              ^^^^^^^^^^ maybe a missing crate `identifier`?

error[E0433]: failed to resolve: maybe a missing crate `identifier`?
   --> bazel-out/k8-fastbuild/bin/Proto/wallet_rust_proto_pb/wallet.rs:211:54
    |
211 |         self.user_id.take().unwrap_or_else(|| super::identifier::Identifier::new())
    |                                                      ^^^^^^^^^^ maybe a missing crate `identifier`?

error[E0433]: failed to resolve: maybe a missing crate `identifier`?
   --> bazel-out/k8-fastbuild/bin/Proto/wallet_rust_proto_pb/wallet.rs:367:140
    |
367 | ...protobuf::types::ProtobufTypeMessage<super::identifier::Identifier>>(
    |                                                ^^^^^^^^^^ maybe a missing crate `identifier`?

error[E0283]: type annotations needed
  --> bazel-out/k8-fastbuild/bin/Proto/wallet_rust_proto_pb/wallet.rs:34:5
   |
34 |     pub user_id: ::protobuf::SingularPtrField<super::identifier::Identifier>,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot infer type
   |
   = note: cannot satisfy `_: Default`
   = note: required by `std::default::Default::default`
   = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to 9 previous errors

Some errors have detailed explanations: E0283, E0433.
For more information about an error, try `rustc --explain E0283`.
ERROR: /home/andrew/KeirosPublic/Proto/BUILD:22:19: output 'Proto/libwallet_rust_proto--1946863109.rlib' was not created
ERROR: /home/andrew/KeirosPublic/Proto/BUILD:22:19: Compiling Rust rlib wallet_rust_proto (2 files) failed: not all outputs were created or valid

```

WORKSPACE 
```
workspace(name = "public_keiros")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

# C++ protocol buffer rules for Bazel.
http_archive(
    name = "rules_cc",
    sha256 = "954b7a3efc8752da957ae193a13b9133da227bdacf5ceb111f2e11264f7e8c95",
    strip_prefix = "rules_cc-9e10b8a6db775b1ecd358d8ddd3dab379a2c29a5",
    urls = ["https://github.com/bazelbuild/rules_cc/archive/9e10b8a6db775b1ecd358d8ddd3dab379a2c29a5.zip"],
)

# rules_java defines rules for generating Java code from Protocol Buffers.
http_archive(
    name = "rules_java",
    sha256 = "ccf00372878d141f7d5568cedc4c42ad4811ba367ea3e26bc7c43445bbc52895",
    strip_prefix = "rules_java-d7bf804c8731edd232cb061cb2a9fe003a85d8ee",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_java/archive/d7bf804c8731edd232cb061cb2a9fe003a85d8ee.tar.gz",
        "https://github.com/bazelbuild/rules_java/archive/d7bf804c8731edd232cb061cb2a9fe003a85d8ee.tar.gz",
    ],
)

# rules_proto defines abstract rules for building Protocol Buffers.
http_archive(
    name = "rules_proto",
    sha256 = "602e7161d9195e50246177e7c55b2f39950a9cf7366f74ed5f22fd45750cd208",
    strip_prefix = "rules_proto-97d8af4dc474595af3900dd85cb3a29ad28cc313",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_proto/archive/97d8af4dc474595af3900dd85cb3a29ad28cc313.tar.gz",
        "https://github.com/bazelbuild/rules_proto/archive/97d8af4dc474595af3900dd85cb3a29ad28cc313.tar.gz",
    ],
)

# language specific rules for building python with Bazel.
http_archive(
    name = "rules_python",
    sha256 = "e5470e92a18aa51830db99a4d9c492cc613761d5bdb7131c04bd92b9834380f6",
    strip_prefix = "rules_python-4b84ad270387a7c439ebdccfd530e2339601ef27",
    urls = ["https://github.com/bazelbuild/rules_python/archive/4b84ad270387a7c439ebdccfd530e2339601ef27.tar.gz"],
)

# the base google protocol buffer code.
http_archive(
    name = "com_google_protobuf",
    sha256 = "60d2012e3922e429294d3a4ac31f336016514a91e5a63fd33f35743ccfe1bd7d",
    strip_prefix = "protobuf-3.11.0",
    urls = ["https://github.com/protocolbuffers/protobuf/archive/v3.11.0.zip"],
)

# gRPC code -- has py_proto_library rule which is useful.
http_archive(
    name = "com_github_grpc_grpc",
    sha256 = "b0d3b876d85e4e4375aa211a52a33b7e8ca9f9d6d97a60c3c844070a700f0ea3",
    strip_prefix = "grpc-1.28.1",
    urls = ["https://github.com/grpc/grpc/archive/v1.28.1.zip"],
)


# proto libraries for grpc. this gives us all the esoteric languages that can be used
http_archive(
    name = "rules_proto_grpc",
   sha256 = "7954abbb6898830cd10ac9714fbcacf092299fda00ed2baf781172f545120419",
    strip_prefix = "rules_proto_grpc-3.1.1",
    urls = ["https://github.com/rules-proto-grpc/rules_proto_grpc/archive/3.1.1.tar.gz"],
)


git_repository(
    name = "upb",
    remote = "https://github.com/protocolbuffers/upb.git",
    commit = "d16bf99ac4658793748cda3251226059892b3b7b",
)

load("@rules_cc//cc:repositories.bzl", "rules_cc_dependencies")

rules_cc_dependencies()

load("@rules_java//java:repositories.bzl", "rules_java_dependencies", "rules_java_toolchains")

rules_java_dependencies()

rules_java_toolchains()

load("@rules_proto//proto:repositories.bzl", "rules_proto_dependencies", "rules_proto_toolchains")

rules_proto_dependencies()

rules_proto_toolchains()

load("@rules_python//python:repositories.bzl", "py_repositories")

py_repositories()

load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")

protobuf_deps()

load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")

grpc_deps()


load("@rules_proto_grpc//:repositories.bzl", "rules_proto_grpc_toolchains", "rules_proto_grpc_repos")
load("@rules_proto_grpc//:repositories.bzl", "rules_proto_grpc_toolchains")
rules_proto_grpc_toolchains()
rules_proto_grpc_repos()

load("@rules_proto//proto:repositories.bzl", "rules_proto_dependencies", "rules_proto_toolchains")
rules_proto_dependencies()
rules_proto_toolchains()

load("@rules_proto_grpc//csharp:repositories.bzl", rules_proto_grpc_csharp_repos = "csharp_repos")

rules_proto_grpc_csharp_repos()

load("@io_bazel_rules_dotnet//dotnet:deps.bzl", "dotnet_repositories")

dotnet_repositories()

load(
    "@io_bazel_rules_dotnet//dotnet:defs.bzl",
    "dotnet_register_toolchains",
    "dotnet_repositories_nugets",
)

dotnet_register_toolchains()

dotnet_repositories_nugets()

load("@rules_proto_grpc//csharp/nuget:nuget.bzl", "nuget_rules_proto_grpc_packages")

nuget_rules_proto_grpc_packages()

# The set of dependencies loaded here is excessive for android proto alone
# (but simplifies our setup)
load("@rules_proto_grpc//android:repositories.bzl", rules_proto_grpc_android_repos = "android_repos")

rules_proto_grpc_android_repos()

load("@rules_jvm_external//:defs.bzl", "maven_install")
load("@io_grpc_grpc_java//:repositories.bzl", "IO_GRPC_GRPC_JAVA_ARTIFACTS", "IO_GRPC_GRPC_JAVA_OVERRIDE_TARGETS", "grpc_java_repositories")

maven_install(
    artifacts = IO_GRPC_GRPC_JAVA_ARTIFACTS,
    generate_compat_repositories = True,
    override_targets = IO_GRPC_GRPC_JAVA_OVERRIDE_TARGETS,
    repositories = [
        "https://repo.maven.apache.org/maven2/",
    ],
)

load("@maven//:compat.bzl", "compat_repositories")

compat_repositories()

grpc_java_repositories()

load("@build_bazel_rules_android//android:sdk_repository.bzl", "android_sdk_repository")

android_sdk_repository(name = "androidsdk")


load("@rules_proto_grpc//d:repositories.bzl", rules_proto_grpc_d_repos = "d_repos")

rules_proto_grpc_d_repos()

load("@io_bazel_rules_d//d:d.bzl", "d_repositories")

d_repositories()


load("@rules_proto_grpc//c:repositories.bzl", rules_proto_grpc_c_repos = "c_repos")

rules_proto_grpc_c_repos()

load("@upb//bazel:workspace_deps.bzl", "upb_deps")

upb_deps()



load("@rules_proto_grpc//js:repositories.bzl", rules_proto_grpc_js_repos = "js_repos")

rules_proto_grpc_js_repos()

load("@build_bazel_rules_nodejs//:index.bzl", "yarn_install")

yarn_install(
    name = "npm",
    package_json = "@rules_proto_grpc//js:requirements/package.json",  # This should be changed to your local package.json which should contain the dependencies required
    yarn_lock = "@rules_proto_grpc//js:requirements/yarn.lock",
)

load("@rules_proto_grpc//objc:repositories.bzl", rules_proto_grpc_objc_repos = "objc_repos")

rules_proto_grpc_objc_repos()



load("@rules_proto_grpc//rust:repositories.bzl", rules_proto_grpc_rust_repos = "rust_repos")

rules_proto_grpc_rust_repos()

load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")

grpc_deps()

load("@rules_rust//rust:repositories.bzl", "rust_repositories")

rust_repositories()

load("@rules_proto_grpc//scala:repositories.bzl", rules_proto_grpc_scala_repos = "scala_repos")

rules_proto_grpc_scala_repos()

load("@io_bazel_rules_scala//:scala_config.bzl", "scala_config")

scala_config()

load("@io_bazel_rules_scala//scala:scala.bzl", "scala_repositories")

scala_repositories()

load("@io_bazel_rules_scala//scala_proto:scala_proto.bzl", "scala_proto_repositories")

scala_proto_repositories()

load("@io_bazel_rules_scala//scala:toolchains.bzl", "scala_register_toolchains")

scala_register_toolchains()

load("@rules_proto_grpc//swift:repositories.bzl", rules_proto_grpc_swift_repos = "swift_repos")

rules_proto_grpc_swift_repos()

load(
    "@build_bazel_rules_swift//swift:repositories.bzl",
    "swift_rules_dependencies",
)

swift_rules_dependencies()

load("@rules_proto_grpc//:repositories.bzl", "bazel_gazelle", "io_bazel_rules_go")  # buildifier: disable=same-origin-load

io_bazel_rules_go()

load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")

go_rules_dependencies()

go_register_toolchains(
    version = "1.15.8",
)

bazel_gazelle()

load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies")

gazelle_dependencies()

load("@rules_proto_grpc//go:repositories.bzl", rules_proto_grpc_go_repos = "go_repos")

rules_proto_grpc_go_repos()



load("@rules_proto_grpc//ruby:repositories.bzl", rules_proto_grpc_ruby_repos = "ruby_repos")

rules_proto_grpc_ruby_repos()

load("@bazelruby_rules_ruby//ruby:deps.bzl", "rules_ruby_dependencies", "rules_ruby_select_sdk")

rules_ruby_dependencies()

rules_ruby_select_sdk(version = "2.7.1")

load("@bazelruby_rules_ruby//ruby:defs.bzl", "ruby_bundle")

ruby_bundle(
    name = "rules_proto_grpc_bundle",
    gemfile = "@rules_proto_grpc//ruby:Gemfile",
    gemfile_lock = "@rules_proto_grpc//ruby:Gemfile.lock",
)


```

Build 
```
load("@rules_proto//proto:defs.bzl", "proto_library")
load("@rules_cc//cc:defs.bzl", "cc_proto_library")
load("@rules_java//java:defs.bzl", "java_proto_library")
load("@com_github_grpc_grpc//bazel:python_rules.bzl", "py_proto_library")
load("@rules_proto_grpc//csharp:defs.bzl", "csharp_proto_library")
load("@rules_proto_grpc//android:defs.bzl", "android_proto_library")
load("@rules_proto_grpc//d:defs.bzl", "d_proto_library")
load("@rules_proto_grpc//c:defs.bzl", "c_proto_library")
load("@rules_proto_grpc//js:defs.bzl", "js_proto_library")
load("@rules_proto_grpc//objc:defs.bzl", "objc_proto_library")
load("@rules_proto_grpc//rust:defs.bzl", "rust_proto_library")
load("@rules_proto_grpc//scala:defs.bzl", "scala_proto_library")
load("@rules_proto_grpc//swift:defs.bzl", "swift_proto_library")
load("@rules_proto_grpc//go:defs.bzl", "go_proto_library")
load("@rules_proto_grpc//ruby:defs.bzl", "ruby_proto_library")

package(default_visibility = ["//visibility:public"])

ruby_proto_library(
    name = "coin_ruby_proto",
    protos = ["coin_proto"]
)

csharp_proto_library(
    name = "coin_csharp_proto.dll",
    protos = ["coin_proto"]
)

c_proto_library(
    name = "coin_c_proto",
    protos = ["coin_proto"]
)

objc_proto_library(
    name = "coin_objc_proto",
    protos = ["coin_proto"],
)

android_proto_library(
    name = "coin_android_proto",
    protos = ["coin_proto"]
)

go_proto_library(
    name = "coin_go_proto",
    protos = ["coin_proto"]
)

swift_proto_library(
    name = "coin_swift_proto",
    protos = ["coin_proto"]
)

scala_proto_library(
    name = "coin_scala_proto",
    protos = ["coin_proto"]
)

rust_proto_library(
    name = "coin_rust_proto",
    protos = ["coin_proto"]
)

js_proto_library(
    name = "coin_js_proto",
    protos = ["coin_proto"]
)

d_proto_library(
    name = "coin_d_proto",
    protos = ["coin_proto"]
)

py_proto_library(
    name = "coin_py_proto",
    deps = ["coin_proto"]
)

java_proto_library(
    name = "coin_java_proto",
    deps = ["coin_proto"],
)

cc_proto_library(
    name = "coin_cc_proto",
    deps = [":coin_proto"],
)

proto_library(
    name = "coin_proto",
    srcs = [":coin.proto"],
    deps = [
    ],
)

```

**Comment by aaliddell** [comment]
It seems odd that so many toolchains are failing, which version of Bazel are you running? Given there are so many dependencies, it may be that you're picking up a set of dependencies that conflict with what is expected in this repo.

**Comment by andrewkatson** [comment]
Bazel 4.0
