### ISSUE TITLE
rules_ruby checksum doesn't match

### ISSUE THREAD

**Issue by nhurden** [rules-proto-grpc/rules_proto_grpc#163]
### Issue Description

Downloading `rules_ruby` fails in this project's own workspace due to a checksum mismatch.

When downloading https://github.com/bazelruby/rules_ruby/archive/v0.5.2.tar.gz I get a `sha256sum` of `a93bf34efa773cd8496ebeeb325c903af1e6634f1fea691fb116018c137a7e07`, which doesn't match https://github.com/rules-proto-grpc/rules_proto_grpc/blob/master/repositories.bzl#L248 .

### Log Output

```plain text
❯ bazel build //csharp/example/routeguide:all
INFO: Repository bazelruby_rules_ruby instantiated at:
  /home/nicholas/repos/rules-proto-grpc/rules_proto_grpc/WORKSPACE:221:11: in <toplevel>
  /home/nicholas/repos/rules-proto-grpc/rules_proto_grpc/ruby/repositories.bzl:11:25: in ruby_repos
  /home/nicholas/repos/rules-proto-grpc/rules_proto_grpc/repositories.bzl:599:24: in bazelruby_rules_ruby
  /home/nicholas/repos/rules-proto-grpc/rules_proto_grpc/repositories.bzl:358:25: in _generic_dependency
Repository rule http_archive defined at:
  /home/nicholas/.cache/bazel/_bazel_nicholas/cc4d5c89b70c7cf6e6deb91eaf4b3317/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
WARNING: Download from https://github.com/bazelruby/rules_ruby/archive/v0.5.2.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Checksum was a93bf34efa773cd8496ebeeb325c903af1e6634f1fea691fb116018c137a7e07 but wanted 793a98624ab659d6ace878d907843b1483bd47cbcc19e99c7eb2df8d6b478492
ERROR: An error occurred during the fetch of repository 'bazelruby_rules_ruby':
   Traceback (most recent call last):
	File "/home/nicholas/.cache/bazel/_bazel_nicholas/cc4d5c89b70c7cf6e6deb91eaf4b3317/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/bazelruby/rules_ruby/archive/v0.5.2.tar.gz] to /home/nicholas/.cache/bazel/_bazel_nicholas/cc4d5c89b70c7cf6e6deb91eaf4b3317/external/bazelruby_rules_ruby/temp11632471564445191386/v0.5.2.tar.gz: Checksum was a93bf34efa773cd8496ebeeb325c903af1e6634f1fea691fb116018c137a7e07 but wanted 793a98624ab659d6ace878d907843b1483bd47cbcc19e99c7eb2df8d6b478492
ERROR: Error fetching repository: Traceback (most recent call last):
	File "/home/nicholas/.cache/bazel/_bazel_nicholas/cc4d5c89b70c7cf6e6deb91eaf4b3317/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/bazelruby/rules_ruby/archive/v0.5.2.tar.gz] to /home/nicholas/.cache/bazel/_bazel_nicholas/cc4d5c89b70c7cf6e6deb91eaf4b3317/external/bazelruby_rules_ruby/temp11632471564445191386/v0.5.2.tar.gz: Checksum was a93bf34efa773cd8496ebeeb325c903af1e6634f1fea691fb116018c137a7e07 but wanted 793a98624ab659d6ace878d907843b1483bd47cbcc19e99c7eb2df8d6b478492
ERROR: no such package '@bazelruby_rules_ruby//ruby': java.io.IOException: Error downloading [https://github.com/bazelruby/rules_ruby/archive/v0.5.2.tar.gz] to /home/nicholas/.cache/bazel/_bazel_nicholas/cc4d5c89b70c7cf6e6deb91eaf4b3317/external/bazelruby_rules_ruby/temp11632471564445191386/v0.5.2.tar.gz: Checksum was a93bf34efa773cd8496ebeeb325c903af1e6634f1fea691fb116018c137a7e07 but wanted 793a98624ab659d6ace878d907843b1483bd47cbcc19e99c7eb2df8d6b478492
INFO: Elapsed time: 0.800s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

### rules_proto_grpc Version

master (b2aa1694e03b9c9e785e9cf9cd844320986656df)

### Bazel Version

4.2.2

### OS

Linux

### Link to Demo Repo

https://github.com/rules-proto-grpc/rules_proto_grpc

**Comment by aaliddell** [comment]
Yep, it looks like rules_ruby reused a tag, which ends up breaking anyone who has already got a hash of the old tag. This is fixed in #152 where rules_ruby is bumped to 6.0.0
