### ISSUE TITLE
Fails to build using Github Actions windows-latest

### ISSUE THREAD

**Issue by s0l0ist** [rules-proto-grpc/rules_proto_grpc#234]
### Issue Description

Fails to import and build the rules because of an illegal char in one of the test sfor workspace names.

### Log Output

```plain text
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@rules_proto_grpc' (requested by nodes 'PACKAGE_LOOKUP:@rules_proto_grpc//', 'PACKAGE_LOOKUP:@rules_proto_grpc//python')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:674)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:382)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: net.starlark.java.eval.Starlark$UncheckedEvalException: InvalidPathException thrown during Starlark evaluation (LOADING)
	at <starlark>.download_and_extract(<builtin>:0)
	at <starlark>._http_archive_impl(C:/users/runneradmin/_bazel_runneradmin/mbljpztt/external/bazel_tools/tools/build_defs/repo/http.bzl:125)
Caused by: java.nio.file.InvalidPathException: Illegal char <"> at index 137: C:/users/runneradmin/_bazel_runneradmin/mbljpztt/external/rules_proto_grpc/test_workspaces/special_characters/path-with-special-chars/a b"!
	at java.base/sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
	at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at java.base/sun.nio.fs.WindowsPath.parse(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
	at java.base/java.nio.file.Path.of(Unknown Source)
	at java.base/java.nio.file.Paths.get(Unknown Source)
```

### rules_proto_grpc Version

4.3.0

### Bazel Version

5.3.2

### OS

Windows

**Comment by aaliddell** [comment]
So the fact that Bazel crashes so abruptly like that should be reported to the Bazel repo, since a more graceful handling of bad paths should be expected. The source of the error appears to be the recently added special shcaracters workspace here: https://github.com/rules-proto-grpc/rules_proto_grpc/tree/master/test_workspaces/special_characters

To fix this it looks like I need to take the " character out of that name, which is frustrating as it is a useful test for bad string interpolation in action generation. I can work around that I think though

**Comment by kevinaud** [comment]
Do you know of any workarounds for this in the meantime? I am unable to build my project on Windows due to this

**Comment by aaliddell** [comment]
> Do you know of any workarounds for this in the meantime? I am unable to build my project on Windows due to this

Could you try using the `dev` branch in your WORKSPACE and report if this resolves the problem?

**Comment by ClintLiddick** [comment]
@aaliddell I was also seeing the error with `path-with-special-chars/a b"`. I was able to test the `dev` branch and that errors has disappeared. 

I don't have a 100% clean build for all the warm-and-fuzzies yet, because Windows CI is new to me, but I'm pretty confident that resolved all Windows issues for rules_proto_grpc.
