### ISSUE TITLE
Python: getting ModuleNotFoundError: No module named 'google.protobuf' when trying to use a library

### ISSUE THREAD

**Issue by rotemtam** [rules-proto-grpc/rules_proto_grpc#74]
I've hit this in a project I'm working on but it is easily reproduced by checking out `master` on this repo and running:
```
bazel run //python/example/routeguide:client
```
the output is:
```
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_rotemtamir/595b813ca51e282a416a8d514023be8e/execroot/rules_proto_grpc/bazel-out/darwin-fastbuild/bin/python/example/routeguide/client.runfiles/rules_proto_grpc/python/example/routeguide/client.py", line 24, in <module>
    from example.proto import routeguide_pb2
  File "/private/var/tmp/_bazel_rotemtamir/595b813ca51e282a416a8d514023be8e/execroot/rules_proto_grpc/bazel-out/darwin-fastbuild/bin/python/example/routeguide/client.runfiles/rules_proto_grpc/python/example/routeguide/routeguide_pb/example/proto/routeguide_pb2.py", line 5, in <module>
    from google.protobuf import descriptor as _descriptor
ModuleNotFoundError: No module named 'google.protobuf'
```

**Comment by rotemtam** [comment]
I managed to track this down to a "dirty" site-packages directory on my global python3 directory on my mac. I had a copy of `google-oauth` that was shadowing `protobuf` from my application.
