### ISSUE TITLE
error AttributeError: module 'typing' has no attribute '_ClassVar' on linux 

### ISSUE THREAD

**Issue by cristifalcas** [rules-proto-grpc/rules_proto_grpc#94]
Wondering if anybody seen this issue here.

I get this strange error on linux machines (works on mac) when building `python_grpclib_library`:

```
ERROR: /home/user/development/Search/tools/proto/BUILD.bazel:8:14: error executing shell command: '/bin/bash -c mkdir -p 'bazel-out/k8-fastbuild/bin/tools/proto/runspec/python_grpclib_compile_aspect_verb0' && bazel-out/host/bin/external/com_google_protobuf/protoc $@  --descriptor_set_in=bazel-ou...' failed (Exit 1): bash failed: error executing command
  (cd /home/user/.cache/bazel/_bazel_user/1be007d6db0b2121058ef5172a230ed1/sandbox/processwrapper-sandbox/2331/execroot/com_company_project && \
  exec env - \
  /bin/bash -c 'mkdir -p '\''bazel-out/k8-fastbuild/bin/tools/proto/runspec/python_grpclib_compile_aspect_verb0'\'' && bazel-out/host/bin/external/com_google_protobuf/protoc $@' '' '--descriptor_set_in=bazel-out/k8-fastbuild/bin/tools/proto/runspec-descriptor-set.proto.bin' '--plugin=protoc-gen-grpclib_python_plugin=bazel-out/k8-opt-exec-2B5CBBC6/bin/external/rules_proto_grpc/python/grpclib/plugin' '--grpclib_python_plugin_out=bazel-out/k8-fastbuild/bin/tools/proto/runspec/python_grpclib_compile_aspect_verb0' tools/proto/run_spec.proto)
Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox bash failed: error executing command
  (cd /home/user/.cache/bazel/_bazel_user/1be007d6db0b2121058ef5172a230ed1/sandbox/processwrapper-sandbox/2331/execroot/com_company_project && \
  exec env - \
  /bin/bash -c 'mkdir -p '\''bazel-out/k8-fastbuild/bin/tools/proto/runspec/python_grpclib_compile_aspect_verb0'\'' && bazel-out/host/bin/external/com_google_protobuf/protoc $@' '' '--descriptor_set_in=bazel-out/k8-fastbuild/bin/tools/proto/runspec-descriptor-set.proto.bin' '--plugin=protoc-gen-grpclib_python_plugin=bazel-out/k8-opt-exec-2B5CBBC6/bin/external/rules_proto_grpc/python/grpclib/plugin' '--grpclib_python_plugin_out=bazel-out/k8-fastbuild/bin/tools/proto/runspec/python_grpclib_compile_aspect_verb0' tools/proto/run_spec.proto)
Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox
Traceback (most recent call last):
  File "/home/user/.cache/bazel/_bazel_user/1be007d6db0b2121058ef5172a230ed1/sandbox/processwrapper-sandbox/2331/execroot/com_company_project/bazel-out/k8-opt-exec-2B5CBBC6/bin/external/rules_proto_grpc/python/grpclib/plugin.runfiles/rules_proto_grpc/python/grpclib/plugin.py", line 1, in <module>
    import grpclib.plugin.main
  File "/home/user/.cache/bazel/_bazel_user/1be007d6db0b2121058ef5172a230ed1/sandbox/processwrapper-sandbox/2331/execroot/com_company_project/bazel-out/k8-opt-exec-2B5CBBC6/bin/external/rules_proto_grpc/python/grpclib/plugin.runfiles/rules_proto_grpc_py3_deps/pypi__grpclib/grpclib/plugin/main.py", line 14, in <module>
    from .. import client
  File "/home/user/.cache/bazel/_bazel_user/1be007d6db0b2121058ef5172a230ed1/sandbox/processwrapper-sandbox/2331/execroot/com_company_project/bazel-out/k8-opt-exec-2B5CBBC6/bin/external/rules_proto_grpc/python/grpclib/plugin.runfiles/rules_proto_grpc_py3_deps/pypi__grpclib/grpclib/client.py", line 22, in <module>
    from .config import Configuration
  File "/home/user/.cache/bazel/_bazel_user/1be007d6db0b2121058ef5172a230ed1/sandbox/processwrapper-sandbox/2331/execroot/com_company_project/bazel-out/k8-opt-exec-2B5CBBC6/bin/external/rules_proto_grpc/python/grpclib/plugin.runfiles/rules_proto_grpc_py3_deps/pypi__grpclib/grpclib/config.py", line 85, in <module>
    @dataclass(frozen=True)
  File "/home/user/.cache/bazel/_bazel_user/1be007d6db0b2121058ef5172a230ed1/sandbox/processwrapper-sandbox/2331/execroot/com_company_project/bazel-out/k8-opt-exec-2B5CBBC6/bin/external/rules_proto_grpc/python/grpclib/plugin.runfiles/rules_proto_grpc_py3_deps/pypi__dataclasses/dataclasses.py", line 950, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
  File "/home/user/.cache/bazel/_bazel_user/1be007d6db0b2121058ef5172a230ed1/sandbox/processwrapper-sandbox/2331/execroot/com_company_project/bazel-out/k8-opt-exec-2B5CBBC6/bin/external/rules_proto_grpc/python/grpclib/plugin.runfiles/rules_proto_grpc_py3_deps/pypi__dataclasses/dataclasses.py", line 801, in _process_class
    for name, type in cls_annotations.items()]
  File "/home/user/.cache/bazel/_bazel_user/1be007d6db0b2121058ef5172a230ed1/sandbox/processwrapper-sandbox/2331/execroot/com_company_project/bazel-out/k8-opt-exec-2B5CBBC6/bin/external/rules_proto_grpc/python/grpclib/plugin.runfiles/rules_proto_grpc_py3_deps/pypi__dataclasses/dataclasses.py", line 801, in <listcomp>
    for name, type in cls_annotations.items()]
  File "/home/user/.cache/bazel/_bazel_user/1be007d6db0b2121058ef5172a230ed1/sandbox/processwrapper-sandbox/2331/execroot/com_company_project/bazel-out/k8-opt-exec-2B5CBBC6/bin/external/rules_proto_grpc/python/grpclib/plugin.runfiles/rules_proto_grpc_py3_deps/pypi__dataclasses/dataclasses.py", line 659, in _get_field
    if (_is_classvar(a_type, typing)
  File "/home/user/.cache/bazel/_bazel_user/1be007d6db0b2121058ef5172a230ed1/sandbox/processwrapper-sandbox/2331/execroot/com_company_project/bazel-out/k8-opt-exec-2B5CBBC6/bin/external/rules_proto_grpc/python/grpclib/plugin.runfiles/rules_proto_grpc_py3_deps/pypi__dataclasses/dataclasses.py", line 550, in _is_classvar
    return type(a_type) is typing._ClassVar
AttributeError: module 'typing' has no attribute '_ClassVar'
--grpclib_python_plugin_out: protoc-gen-grpclib_python_plugin: Plugin failed with status code 1.
```

**Comment by cristifalcas** [comment]
So strange, that dependency (dataclasses) is only added on linux and not on mac

**Comment by aaliddell** [comment]
Which Python versions are you running on the working and non-working systems?

**Comment by wangping886** [comment]
i met this problem, it's python>3.7 don't need this package. and i remove this package , it sovles.
